# verify that application Javascript files are lintable
# see https://github.com/psionides/jslint_on_rails
guard 'jshint-on-rails' do
  # watch for changes to application javascript files
  watch(%r{^app/assets/javascripts/.*\.js$})
end
