# verify that application Javascript files are lintable
# see https://github.com/stereobooster/jshintrb
guard 'jshint-on-rails' do
  # watch for changes to application javascript files
  watch(%r{^app/assets/javascripts/.*\.js$})
  watch(%r{^vendor/assets/javascripts/.*\.js$})
  watch(%r{^public/.*\.js$})
end
